name: poloniex_connection_example
description: Example of connection to Poloniex trading (private) API.
# version: 1.0.0
# author: Kyrylo Shamraiev <makdir@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  crypto: ^2.1.3
  http: ^0.12.0+4


dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
